<?php 

/**
 * Implements hook_block_view_alter().
 */
function ib_task_56_block_view_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {
  switch ($build['#id']) {
    // Machine name 
    case 'ib_task_56':
      $build['#attached']['library'][] = 'core/drupal.dialog.ajax';
      
  }
}

/**
 * Implements hook_theme().
 */
function ib_task_56_theme($existing, $type, $theme, $path) {
  return [
    'block-template' => [
            'variables' => ['variable' => NULL],
            'templates' => 'block-template',
        ],
  ];
}
